# Generated by Django 2.0.2 on 2018-02-16 21:55

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patches', '0002_userstate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='item',
            new_name='showing',
        ),
        migrations.AlterField(
            model_name='userstate',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
