# Generated by Django 2.0.2 on 2018-02-16 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patches', '0003_auto_20180216_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='showing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patches.Showing'),
        ),
    ]
